language: c

# Use the faster container-based infrastructure.
sudo: false

addons:
  apt:
    packages:
      - libevent-dev
      - liblua5.2-dev
      - libsqlite3-dev
      - libssl-dev

matrix:
   include:
      - compiler: gcc
        os: linux
      - compiler: clang
        os: linux
      - compiler: clang
        os: osx

# brew stuff for macOS
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          	       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libevent lua sqlite ; fi

# compile script
before_script: ./autogen.sh
script: ./configure --enable-debug --enable-lua --enable-quotes && make

