language: c

# Use the faster container-based infrastructure.
sudo: false

addons:
  apt:
    packages:
      - libevent-dev
      - liblua5.2-dev
      - libsqlite3-dev
      - libssl-dev

matrix:
   include:
      - compiler: gcc
        os: linux
      - compiler: clang
        os: linux
      - compiler: clang
        os: osx
        osx_image: xcode8.2

# brew stuff for macOS
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew unlink libevent ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libevent sqlite	openssl ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link --force openssl ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CPPFLAGS=-I$(brew --prefix openssl)/include; export LDFLAGS=-L$(brew --prefix openssl)/include ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then openssl version ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sqlite3 --version ; fi

# compile script
before_script: ./autogen.sh
script: 
  - ./configure --enable-debug --enable-quotes
  - make

