language: c

# Use the faster container-based infrastructure.
sudo: false

script: ./configure --enable-debug --enable-quotes && make

addons:
  apt:
    packages:
      - libevent-dev
      - libsqlite3-dev
      - libssl-dev

matrix:
   include:
      - compiler: gcc
        os: linux
      - compiler: clang
        os: linux
